---
title: <center>R练习1</center>
author: <center>薛贵林</center>
date: <center>2020/5/18</center>
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,#用于显示代码，不显示就false
  tidy = TRUE,#使得代码排版更整洁
  warning = FALSE,#去掉运算结果得到waring信息
  comment = ' ',#去掉运算结果的“#”号
  message = FALSE,#去掉运算结果的提示信息
  collapse = TRUE,#让一个代码块放在一起
  prompt = TRUE#代码开头以大于号开始
  )
```

## 向量操作
```{r}
v<-c(1,4,4,3,2,2,3)
(v[c(2,3,4)])
v[2:4] 
v[c(2,4,3)]
v[-2] 
v[-2:-4]
v[v<3]
which(v==3)
x<-1:3
print(x^2)
cat(x^2)
seq(1,5,1)
seq(1,by=3,length=5)
rep(c(1,2,3),3)
rep(c(1,2,3),each=3)
rep(1:3,rep(1,2,3))
w <-'Display"b"string' 
w
cat(w)
z<-'ABCD"E"FG'
cat(z)
```


## 矩阵操作
```{r}
y <- matrix(1:20, nrow=5, ncol=4)
y
x <- matrix(1:10, nrow=2)
x
x[2,]
x[,2]
x[1,4]
x[1,c(4,5)]
x[2,1:3]
y <- matrix(1:20, nrow=5, ncol=4,byrow=TRUE)
y
rnames=c("apple","banana","orange","melon","watermelon")
cnames=c("cat","dog","bird","pig")
x = matrix(1:20, nrow=5, ncol=4, byrow=TRUE)
rownames(x)=rnames
colnames(x)=cnames
knitr::kable(x)
dim1 = c("A1", "A2")
dim2 = c("B1", "B2", "B3")
dim3 = c("C1", "C2", "C3", "C4")
dim4 = c("D1", "D2", "D3")
```

## 数组操作与数据框data.frame引入
```{r}
z <- array(1:72, c(2, 3, 4, 3), dimnames=list(dim1, dim2, dim3, dim4))
head(z)
z[1,2,3,]
ID<-c(1,2,3,4)
age<-c(20,21,22,23)
sex<-c("女","男","女","男")
height<-c(165,180,160,175)
weight<-c(45,70,40,65)
data<-data.frame(ID,age,sex,height,weight)
knitr::kable(data)
data[1:2]
data[c("ID","sex")]
table(data$ID,data$age)
diag(3)
diag(x)
diag(1:3)
a<-list(name="xueguilin",age=20,scores=c(100,100,100))
a
a[[2]]
a[[3]][2]
```



