---
title: <center>R练习2</center>
author: <center>薛贵林</center>
date: <center>2020/5/18</center>
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,#用于显示代码，不显示就false
  tidy = TRUE,#使得代码排版更整洁
  warning = FALSE,#去掉运算结果得到waring信息
  comment = ' ',#去掉运算结果的“#”号
  message = FALSE,#去掉运算结果的提示信息
  collapse = TRUE,#让一个代码块放在一起
  prompt = TRUE#代码开头以大于号开始
  )
```

## 类型转换，因子，数据框转换
```{r}
M<-matrix(1:12,nrow=3,ncol=4)
class(M)
M.vec<-as.numeric(M)
M.vec
class(M.vec)
M.frame<-as.data.frame(M)
M.frame
A<-factor(c(1:4),levels =c(1,2))
A
```

## 数据框构建和数据筛选 
```{r}
patientID <- c(1, 2, 3, 4)
age <- c(20, 21, 22, 23)
diabetes <- c("Type1", "Type2", "Type1", "Type1")
status <- c("Poor", "Improved", "Excellent", "Poor")
diabetes <- factor(diabetes)
status <- factor(status, order=TRUE)
patientdata <- data.frame(patientID, age, diabetes, status)
patientdata
summary(patientdata)
patientdata$height<-c(169,155,175,180)
patientdata
is.na(patientdata)
u<-patientdata
patientdata$height<-NULL
u
v<-subset(patientdata,age>21)
v
```


## 矩阵操作
```{r}
x<-c(1,2)*2
x
##
set.seed(123)
A = matrix(sample(100,15), nrow=5, ncol=3)
set.seed(234)
B = matrix(sample(100,15), nrow=5, ncol=3)
set.seed(321)
X = matrix(sample(100,25), nrow=5, ncol=5)
set.seed(213)
b = matrix(sample(100,5),nrow=5, ncol=1)
A
B
X
b
A + 2
A ^ 2
t(A) %*% B 
colMeans(A)
colSums(A)
rowMeans(A)
rowSums(A)
dim(A)
rbind(A,B)
cbind(A,B)
apply(A,1,sum)
apply(A,2,sum)
```


## apply族函数例子
```{r}
manager <- c(1, 2, 3, 4, 5)
country <- c("CN", "US", "CN", "CN", "US")
gender <- c("M", "F", "F", "M", "F")
age <- c(30, 45, 40, 52, 21)
leadership <- data.frame(manager, country, gender, age)
leadership
tapply(age,country,median)
b <- list(x = 1:10, y = matrix(1:12, nrow=3, ncol=4))
b
lapply(b, sum)	
```

## 数据筛选和正态随机数生成
```{r}
x<-1==2
as.numeric(x)
x<-0:10
g<-(x>5|x<1)
g
g<-(x>5&x<1)
g
m<-c(1,3,0,2,5,4)
max(m)
min(m)
median(m)
##
runif(4)
rnorm(10)
rnorm(10,mean=1,sd=4)

