install.packages('dplyr')
#所有城市的冠状病毒分布
library(devtools)
install_github("GuangchuangYu/nCov2019",force = TRUE)
library(leafletCN)
require(nCov2019)
library(dplyr)
library(ggplot2)
ppp <- get_nCov2019()
ppp
x[]
a<-unlist(x['广东', ][3])%>%as.numeric()
b<-unlist(x['广西', ][3])%>%as.numeric()
c<-unlist(x['新疆', ][3])%>%as.numeric()
e<-unlist(x['澳门', ][3])%>%as.numeric()
f<-unlist(x['香港', ][3])%>%as.numeric()
g<-unlist(x['海南', ][3])%>%as.numeric()
h<-unlist(x['福建', ][3])%>%as.numeric()
i<-unlist(x['湖南', ][3])%>%as.numeric()
j<-unlist(x['江西', ][3])%>%as.numeric()
k<-unlist(x['云南', ][3])%>%as.numeric()
l<-unlist(x['贵州', ][3])%>%as.numeric()
m<-unlist(x['四川', ][3])%>%as.numeric()
n<-unlist(x['重庆', ][3])%>%as.numeric()
o<-unlist(x['浙江', ][3])%>%as.numeric()
p<-unlist(x['台湾', ][3])%>%as.numeric()
q<-unlist(x['上海', ][3])%>%as.numeric()
r<-unlist(x['安徽', ][3])%>%as.numeric()
s<-unlist(x['江苏', ][3])%>%as.numeric()
t<-unlist(x['河南', ][3])%>%as.numeric()
u<-unlist(x['山东', ][3])%>%as.numeric()
v<-unlist(x['陕西', ][3])%>%as.numeric()
w<-unlist(x['山西', ][3])%>%as.numeric()
a0<-unlist(x['宁夏', ][3])%>%as.numeric()
y<-unlist(x['甘肃', ][3])%>%as.numeric()
z<-unlist(x['青海', ][3])%>%as.numeric()
aa<-unlist(x['内蒙古', ][3])%>%as.numeric()
bb<-unlist(x['北京', ][3])%>%as.numeric()
cc<-unlist(x['黑龙江', ][3])%>%as.numeric()
dd<-unlist(x['天津', ][3])%>%as.numeric()
ee<-unlist(x['河北', ][3])%>%as.numeric()
ff<-unlist(x['山东', ][3])%>%as.numeric()
gg<-unlist(x['辽宁', ][3])%>%as.numeric()
hh<-unlist(x['吉林', ][3])%>%as.numeric()
b2<-c(a,b,c,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,a0,y,z,aa,bb,cc,dd,ee,ff,gg,hh)

a1<-unlist(x['广东', ][1])%>%as.character()
b1<-unlist(x['广西', ][1])%>%as.character()
c1<-unlist(x['新疆', ][1])%>%as.character()
e1<-unlist(x['澳门', ][1])%>%as.character()
f1<-unlist(x['香港', ][1])%>%as.character()
g1<-unlist(x['海南', ][1])%>%as.character()
h1<-unlist(x['福建', ][1])%>%as.character()
i1<-unlist(x['湖南', ][1])%>%as.character()
j1<-unlist(x['江西', ][1])%>%as.character()
k1<-unlist(x['云南', ][1])%>%as.character()
l1<-unlist(x['贵州', ][1])%>%as.character()
m1<-unlist(x['四川', ][1])%>%as.character()
n1<-unlist(x['重庆', ][1])%>%as.character()
o1<-unlist(x['浙江', ][1])%>%as.character()
p1<-unlist(x['台湾', ][1])%>%as.character()
q1<-unlist(x['上海', ][1])%>%as.character()
r1<-unlist(x['安徽', ][1])%>%as.character()
s1<-unlist(x['江苏', ][1])%>%as.character()
t1<-unlist(x['河南', ][1])%>%as.character()
u1<-unlist(x['山东', ][1])%>%as.character()
v1<-unlist(x['陕西', ][1])%>%as.character()
w1<-unlist(x['山西', ][1])%>%as.character()
x1<-unlist(x['宁夏', ][1])%>%as.character()
y1<-unlist(x['甘肃', ][1])%>%as.character()
z1<-unlist(x['青海', ][1])%>%as.character()
aa1<-unlist(x['内蒙古', ][1])%>%as.character()
bb1<-unlist(x['北京', ][1])%>%as.character()
cc1<-unlist(x['黑龙江', ][1])%>%as.character()
dd1<-unlist(x['天津', ][1])%>%as.character()
ee1<-unlist(x['河北', ][1])%>%as.character()
ff1<-unlist(x['山东', ][1])%>%as.character()
gg1<-unlist(x['辽宁', ][1])%>%as.character()
hh1<-unlist(x['吉林', ][1])%>%as.character()

c2<-c(a1,b1,c1,e1,f1,g1,h1,i1,j1,k1,l1,m1,n1,o1,p1,q1,r1,s1,t1,u1,v1,w1,x1,y1,z1,aa1,bb1,cc1,dd1,ee1,ff1,gg1,hh1)
c2
d2<-as.data.frame(b2,c2)
d2
ggplot(d2,aes(x=c2,y=b2))+
  geom_point(show.legend=T,alpha=0.8)+
  labs(x="城市",y="确诊人数")
write.csv(d2,"d2.csv")

a<-unlist(x[ ][3])%>%as.numeric()
a
a1<-unlist(x[ ][1])%>%as.character()
a1
b<-cbind.data.frame(a1,a)
#用于数据框改名
names(b)<-c('name','value')
write.csv(b,file = "b.csv")

library(ggplot2)
library(ggimage)
d <- data.frame(x = rnorm(10),
                y = rnorm(10),
                image = sample(c("https://www.r-project.org/logo/Rlogo.png",
                                 "https://jeroenooms.github.io/images/frink.png"),
                               size=10, replace = TRUE))
ggplot(d, aes(x, y)) + geom_image(aes(image=image), size=.05)
