library('rvest')
web<-read_html('https://www.thepaper.cn/')
news<-web%>%html_nodes('h2 a')
title<-news%>%html_text()
link<-news%>%html_attrs()
link3<-paste("https://www.thepaper.cn/",link[[3]][1],sep="")
news_con<-read_html(link3)%>%html_nodes('div.news_txt')%>%html_text()
install.packages('jiebaR')
library(jiebaR)
